import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, Database, Thermometer, ArrowRight, BarChart3, Download } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { API_BASE_URL, WS_BASE_URL } from "@/config/api";
import { motion } from "motion/react";
import AnimatedThermometer from "@/components/dashboard/AnimatedThermometer";


const Index = () => {
  const navigate = useNavigate();
  const isAuthenticated = localStorage.getItem("isAuthenticated") === "true";

  return (
    <div className="min-h-screen bg-dashboard-bg">
      <div className="container mx-auto px-6 py-12">
        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="text-center space-y-6 mb-12"
        >
          <div className="flex items-center justify-center gap-3 mb-4">
            <AnimatedThermometer value={32} />
            <h1 className="text-5xl font-bold text-dashboard-text-primary">
              Radix-IoT : Temperature Monitoring
            </h1>
          </div>
          <p className="text-xl text-dashboard-text-secondary max-w-2xl mx-auto">
            Real-time temperature monitoring dashboard backed by RadixIoT FastAPI Backend with WebSocket data feeds and historical analysis using data generated by UMX201 ETH Scanner
          </p>
          <div className="flex items-center justify-center gap-4 pt-4">
            {isAuthenticated ? (
              <Link to="/dashboard">
                <Button size="lg" className="flex items-center gap-2 bg-primary hover:bg-primary/90">
                  <Activity className="h-5 w-5" />
                  Launch Dashboard
                  <ArrowRight className="h-5 w-5" />
                </Button>
              </Link>
            ) : (
              <Button 
                size="lg" 
                onClick={() => navigate('/auth')}
                className="flex items-center gap-2 bg-primary hover:bg-primary/90"
              >
                Login / Register
                <ArrowRight className="h-5 w-5" />
              </Button>
            )}
          </div>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12"
        >
          <Card className="dashboard-card group hover:shadow-lg transition-all duration-300">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-dashboard-text-primary">
                <Activity className="h-6 w-6 text-primary group-hover:animate-pulse" />
                Real-Time Monitoring
              </CardTitle>
              <CardDescription className="text-dashboard-text-secondary">
                Live WebSocket data feed from your temperature sensors
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-success rounded-full animate-pulse"></div>
                8-Channel temperature gauges
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-success rounded-full animate-pulse"></div>
                Live temperature charts
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-success rounded-full animate-pulse"></div>
                Raw register data display
              </div>
            </CardContent>
          </Card>

          <Card className="dashboard-card group hover:shadow-lg transition-all duration-300">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-dashboard-text-primary">
                <Database className="h-6 w-6 text-chart-2 group-hover:animate-pulse" />
                Historical Analysis
              </CardTitle>
              <CardDescription className="text-dashboard-text-secondary">
                Comprehensive data analysis and filtering tools
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-2 rounded-full"></div>
                Date range filtering
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-2 rounded-full"></div>
                Device-specific data
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-2 rounded-full"></div>
                Detailed data tables
              </div>
            </CardContent>
          </Card>

          <Card className="dashboard-card group hover:shadow-lg transition-all duration-300">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-dashboard-text-primary">
                <Download className="h-6 w-6 text-chart-3 group-hover:animate-pulse" />
                Data Export
              </CardTitle>
              <CardDescription className="text-dashboard-text-secondary">
                Multiple export formats for your measurement data
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-3 rounded-full"></div>
                Excel (.xlsx) format
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-3 rounded-full"></div>
                CSV data export
              </div>
              <div className="flex items-center gap-2 text-sm text-dashboard-text-secondary">
                <div className="w-2 h-2 bg-chart-3 rounded-full"></div>
                JSON raw data
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Quick Stats */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
        >
          <Card className="dashboard-card mb-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-3 text-dashboard-text-primary">
                <BarChart3 className="h-6 w-6 text-primary" />
                System Overview
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-primary">8</div>
                  <div className="text-sm text-dashboard-text-secondary">Temperature Channels</div>
                </div>
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-chart-2">Real-time</div>
                  <div className="text-sm text-dashboard-text-secondary">Data Updates</div>
                </div>
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-chart-3">Multi</div>
                  <div className="text-sm text-dashboard-text-secondary">Export Formats</div>
                </div>
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-chart-4">24/7</div>
                  <div className="text-sm text-dashboard-text-secondary">Monitoring</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Connection Info */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
        >
          <Card className="dashboard-card">
            <CardHeader>
              <CardTitle className="text-dashboard-text-primary">Backend Configuration</CardTitle>
              <CardDescription className="text-dashboard-text-secondary">
                System endpoints and connection details
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid md:grid-cols-2 gap-4 text-sm">
                <div>
                  <strong className="text-dashboard-text-primary">WebSocket Feed:</strong>
                  <code className="block mt-1 p-2 bg-background/50 rounded text-dashboard-text-secondary font-mono">
                    {`${WS_BASE_URL}/ws/frontend`}
                  </code>
                </div>
                <div>
                  <strong className="text-dashboard-text-primary">REST API Feed Historical:</strong>
                  <code className="block mt-1 p-2 bg-background/50 rounded text-dashboard-text-secondary font-mono">
                    {`${API_BASE_URL}/measurements`}
                  </code>
                </div>
                <div>
                  <strong className="text-dashboard-text-primary">REST API Feed Live:</strong>
                  <code className="block mt-1 p-2 bg-background/50 rounded text-dashboard-text-secondary font-mono">
                    {`${API_BASE_URL}/data`}
                  </code>
                </div>
              </div>
              <p className="text-xs text-dashboard-text-muted">
                Make sure your FastAPI backend is running on localhost:8000 before accessing the dashboard
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
};

export default Index;
