name: Build and Release Radix Gateway (Windows)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'GitHub Tag Name (e.g., v1.0.0). Required for release upload.'
        required: true
        type: string

jobs:
  build-release-windows:
    name: Build & Upload Windows Executables
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./gateway

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag_name || github.ref_name }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create virtual environment
      shell: powershell
      run: |
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1

    - name: Install dependencies
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install pyinstaller

    - name: Build GUI Executable (gateway.py)
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile --windowed --icon=assets/logo.ico --add-data "assets;assets" gateway.py
        Move-Item -Path .\dist\gateway* -Destination .\dist\gateway-gui-windows.exe

    - name: Build Headless Executable (gateway_headless.py)
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile gateway_headless.py
        Move-Item -Path .\dist\gateway_headless* -Destination .\dist\gateway-headless-windows.exe

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        files: ./dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
