name: Build and Release Radix Gateway

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'GitHub Tag Name (e.g., v1.0.0). Required for release upload.'
        required: true
        type: string

jobs:
  build-release:
    name: Build & Upload Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.10']

    defaults:
      run:
        working-directory: ./gateway

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag_name || github.ref_name }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1

    - name: Create virtual environment (Linux/macOS)
      if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install pyinstaller

    - name: Install dependencies (Linux/macOS)
      if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller

    # Build GUI executable
    - name: Build GUI Executable (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile --windowed --icon=assets/logo.ico --add-data "assets;assets" gateway.py
        Move-Item -Path .\dist\gateway* -Destination .\dist\gateway-gui-windows.exe

    - name: Build GUI Executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        source .venv/bin/activate
        pyinstaller --onefile --windowed --icon=assets/logo.ico --add-data "assets:assets" gateway.py
        mv ./dist/gateway* ./dist/gateway-gui-linux

    - name: Build GUI Executable (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        source .venv/bin/activate
        pyinstaller --onefile --windowed --icon=assets/logo.ico --add-data "assets:assets" gateway.py
        mv ./dist/gateway* ./dist/gateway-gui-macos

    # Build Headless executable
    - name: Build Headless Executable (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile gateway_headless.py
        Move-Item -Path .\dist\gateway_headless* -Destination .\dist\gateway-headless-windows.exe

    - name: Build Headless Executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        source .venv/bin/activate
        pyinstaller --onefile gateway_headless.py
        mv ./dist/gateway_headless* ./dist/gateway-headless-linux

    - name: Build Headless Executable (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        source .venv/bin/activate
        pyinstaller --onefile gateway_headless.py
        mv ./dist/gateway_headless* ./dist/gateway-headless-macos

    # Upload all executables to release
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        files: ./dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
