name: Build and Release Radix Gateway (Windows)

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
      
permissions:
  contents: write 

jobs:
  build-release-windows:
    name: Build & Upload Windows Executables
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./gateway

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create virtual environment
      shell: powershell
      run: |
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1

    - name: Install dependencies
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install pyinstaller

    - name: Build GUI Executable (gateway.py)
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile --windowed --icon=assets/logo.ico --add-data "assets;assets" gateway.py
        Move-Item -Path .\dist\gateway* -Destination .\dist\gateway-gui-windows.exe

    - name: Build Headless Executable (gateway_headless.py)
      shell: powershell
      run: |
        .\.venv\Scripts\Activate.ps1
        pyinstaller --onefile gateway_headless.py
        Move-Item -Path .\dist\gateway_headless* -Destination .\dist\gateway-headless-windows.exe

    - name: Determine release tag
      id: release_tag
      run: |
        if ($env:GITHUB_REF -like "refs/tags/*") {
          echo "tag_name=${env:GITHUB_REF#refs/tags/}" >> $env:GITHUB_ENV
        } else {
          echo "tag_name=snapshot" >> $env:GITHUB_ENV
        }

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag_name }}
        files: ./dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
